// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Thu Jan 06 2022 15:39:13 GMT+0100 (heure normale d’Europe centrale)",
    message: null,
    git: {
        user: "Jean-Louis GUÉNÉGO",
        branch: "master",
        hash: "517677",
        fullHash: "517677631a9a246d31e09bf7abe150fe462b37e2"
    }
};

export default build;