// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Fri Jan 07 2022 12:03:22 GMT+0100 (heure normale d’Europe centrale)",
    message: null,
    git: {
        user: "Jean-Louis GUÉNÉGO",
        branch: "master",
        hash: "21d9c9",
        fullHash: "21d9c93d1cbbf732e3979b7b2ee8292fc00cdf59"
    }
};

export default build;