// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Wed Mar 30 2022 16:30:54 GMT+0200 (heure d’été d’Europe centrale)",
    message: null,
    git: {
        user: "Jean-Louis GUÉNÉGO",
        branch: "master",
        hash: "f0296e",
        fullHash: "f0296efc271650714cdb522c9e1363879b2dfaf0"
    }
};

export default build;